# Generated by Django 4.2.1 on 2023-05-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckedSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=300)),
                ('context', models.JSONField()),
                ('ads', models.JSONField()),
                ('name', models.TextField(max_length=100)),
                ('user_agent', models.TextField(max_length=300)),
                ('file', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='InputSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=300)),
                ('query', models.TextField(blank=True, max_length=100, null=True)),
                ('search', models.TextField(blank=True, max_length=100, null=True)),
                ('user_agent', models.TextField(max_length=300)),
                ('context', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
